apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-cvnj
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-cvnj
    app.kubernetes.io/part-of: devfile-sample-1
  name: devfile-sample-cvnj
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-cvnj
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-cvnj
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhn-support-marrober-tenant/devfile-sample-1/devfile-sample-cvnj@sha256:3f95444df653be77cfdf251bf00b3f58bde9af608d4cf7df739355b0eccd93e2
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
